version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      version_updates:
        applies-to: version-updates
      security_updates:
        applies-to: security-updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
