import "./globals.css"
import NavBar from "./NavBar";
import Footer from "./Footer";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className="dark">
        <NavBar />
        {children}
        <Footer />
      </body>

    </html>
  )
}
